
# Build DataWave

- debug:
    msg: "DataWave build command: {{ dw_build_command }}"

- name: "build datawave {{ dw_project_version }}"
  shell: "source ~/.bash_profile && {{ dw_build_command }} > /tmp/datawave-build.out"
  args:
    executable: /bin/bash
    chdir: "{{ dw_clone_dir }}"
