- name: "start mapred job history server"
  shell: "source ~/.bash_profile && ./mr-jobhistory-daemon.sh start historyserver"
  args:
    executable: /bin/bash
    chdir: "{{ hadoop_home }}/sbin"
  register: historyserver_stat
  changed_when: "'starting historyserver' in historyserver_stat.stdout"
  failed_when: "historyserver_stat.rc != 0 and 'historyserver running as process' not in historyserver_stat.stdout"
