# Bounce Accumulo and execute configured shell tasks on start
- hosts: accumulomaster
  roles:
    - accumulo
  tasks:
    - name: "stop accumulo"
      shell: "{{ accumulo_home }}/bin/stop-all.sh"
      register: stop_result
      changed_when: "'Stopping' in stop_result.stdout"
      tags: [stop-accumulo]

    - name: "start accumulo"
      shell: "{{ accumulo_home }}/bin/start-all.sh"
      register: start_result
      changed_when: "'Starting' in start_result.stdout"
      notify: "accumulo shell tasks"
      tags: [start-accumulo]
  handlers:
    - include: roles/accumulo/handlers/accumulo-shell-tasks.yml
      when: dw_accumulo_skip_shell_tasks == False
